{{ $rules := .Files.Get "generated/role.yaml" | fromYaml -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: {{ include "chart.fullname" . }}
rules:
{{ get $rules "rules" | toYaml | indent 2 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: {{ include "chart.fullname" . }}
rules:
{{ get $rules "rules" | toYaml | indent 2 }}