---
name: shipwright
description: set up shipwright build controller on a kind instance
runs:
  using: composite
  steps:
    - uses: helm/kind-action@v1.4.0
      with:
        version: v0.14.0
        cluster_name: kind
        wait: 120s
    - uses: shipwright-io/setup@v1
