---
name: shipwright
description: set up shipwright build controller on a kind instance
runs:
  using: composite
  steps:
    - uses: helm/kind-action@v1.2.0
      with:
        version: v0.14.0
        cluster_name: kind
        wait: 120s
    - shell: bash
      run: make verify-kind
    - uses: azure/setup-kubectl@v1
    - uses: imjasonh/setup-ko@v0.4
    - shell: bash
      run: make install-shipwright
