name: Test

on:
  push:
    tags-ignore:
      - "**"
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit:
    runs-on: ubuntu-latest
    name: unit
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          go-version: '1.20.x'
      - name: test-unit
        run: make test-unit
  integration:
    runs-on: ubuntu-latest
    name: integration
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          go-version: '1.20.x'
      - name: test-integration
        run: make test-integration

  # test-e2e:
  #   name: test-e2e
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: ./.github/actions/setup
  #     - uses: ./.github/actions/shipwright

  #     - name: test-e2e
  #       run: make test-e2e
